# Generated by Django 5.2.6 on 2025-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('accessories', 'Accessories'), ('ball', 'Ball')], default='update', max_length=250),
        ),
    ]
