# Generated by Django 5.2.6 on 2025-09-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stok',
            field=models.IntegerField(default=0),
        ),
    ]
